export const colors = {
  surface: '#f7fafc',
  surfaceDim: '#d7dadc',
  surfaceBright: '#f7fafc',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f1f4f6',
  surfaceContainer: '#ebeef0',
  surfaceContainerHigh: '#e5e9eb',
  onSurface: '#181c1e',
  onSurfaceVariant: '#424752',
  outline: '#727784',
  outlineVariant: '#c2c6d4',
  primary: '#003f87',
  onPrimary: '#ffffff',
  primaryContainer: '#0056b3',
  onPrimaryContainer: '#bbd0ff',
  primaryFixed: '#d7e2ff',
  primaryFixedDim: '#acc7ff',
  onPrimaryFixed: '#001a40',
  selectedSurface: '#e8efff',
  secondary: '#924c00',
  onSecondary: '#ffffff',
  secondaryContainer: '#f88400',
  onSecondaryContainer: '#5b2d00',
  secondaryFixed: '#ffdcc4',
  onSecondaryFixed: '#2f1400',
  tertiary: '#384253',
  tertiaryFixedDim: '#bdc7dc',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  safeGreen: '#16a34a',
  talkBackBlue: '#115cb9',
  background: '#f7fafc',
} as const;

export const spacing = {
  edge: 20,
  touchMin: 48,
  gutter: 16,
} as const;
