export const colors = {
  surface: '#f8fafc',
  surfaceDim: '#e2e8f0',
  surfaceBright: '#ffffff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f1f5f9',
  surfaceContainer: '#e2e8f0',
  surfaceContainerHigh: '#cbd5e1',
  onSurface: '#0f172a',
  onSurfaceVariant: '#475569',
  outline: '#94a3b8',
  outlineVariant: '#cbd5e1',
  primary: '#2563eb', // Vibrant, modern blue
  onPrimary: '#ffffff',
  primaryContainer: '#dbeafe',
  onPrimaryContainer: '#1e3a8a',
  primaryFixed: '#bfdbfe',
  primaryFixedDim: '#93c5fd',
  onPrimaryFixed: '#172554',
  selectedSurface: '#eff6ff',
  secondary: '#0ea5e9', // Modern cyan-blue
  onSecondary: '#ffffff',
  secondaryContainer: '#e0f2fe',
  onSecondaryContainer: '#082f49',
  secondaryFixed: '#bae6fd',
  onSecondaryFixed: '#0c4a6e',
  tertiary: '#3b82f6',
  tertiaryFixedDim: '#60a5fa',
  error: '#ef4444',
  onError: '#ffffff',
  errorContainer: '#fee2e2',
  onErrorContainer: '#7f1d1d',
  safeGreen: '#22c55e',
  talkBackBlue: '#2563eb',
  background: '#f8fafc',
} as const;

export const spacing = {
  edge: 20,
  touchMin: 48,
  gutter: 16,
} as const;
